version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - BASE_DOMAIN=http://localhost:5000
    networks:
      - shortify-net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - shortify-net

networks:
  shortify-net:
    driver: bridge
